"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Worlds;
(function (Worlds) {
    let Elemental;
    (function (Elemental) {
        Elemental["Aegis"] = "Aegis";
        Elemental["Atomos"] = "Atomos";
        Elemental["Carbuncle"] = "Carbuncle";
        Elemental["Garuda"] = "Garuda";
        Elemental["Gungnir"] = "Gungnir";
        Elemental["Kujata"] = "Kujata";
        Elemental["Ramuh"] = "Ramuh";
        Elemental["Tonberry"] = "Tonberry";
        Elemental["Typhon"] = "Typhon";
        Elemental["Unicorn"] = "Unicorn";
    })(Elemental = Worlds.Elemental || (Worlds.Elemental = {}));
    let Gaia;
    (function (Gaia) {
        Gaia["Alexander"] = "Alexander";
        Gaia["Bahamut"] = "Bahamut";
        Gaia["Durandal"] = "Durandal";
        Gaia["Fenrir"] = "Fenrir";
        Gaia["Ifrit"] = "Ifrit";
        Gaia["Ridill"] = "Ridill";
        Gaia["Tiamat"] = "Tiamat";
        Gaia["Ultima"] = "Ultima";
        Gaia["Valefor"] = "Valefor";
        Gaia["Yojimbo"] = "Yojimbo";
        Gaia["Zeromus"] = "Zeromus";
    })(Gaia = Worlds.Gaia || (Worlds.Gaia = {}));
    let Mana;
    (function (Mana) {
        Mana["Anima"] = "Anima";
        Mana["Asura"] = "Asura";
        Mana["Belias"] = "Belias";
        Mana["Chocobo"] = "Chocobo";
        Mana["Hades"] = "Hades";
        Mana["Ixion"] = "Ixion";
        Mana["Mandragora"] = "Mandragora";
        Mana["Masamune"] = "Masamune";
        Mana["Pandaemonium"] = "Pandaemonium";
        Mana["Shinryu"] = "Shinryu";
        Mana["Titan"] = "Titan";
    })(Mana = Worlds.Mana || (Worlds.Mana = {}));
    let Aether;
    (function (Aether) {
        Aether["Adamantoise"] = "Adamantoise";
        Aether["Balmung"] = "Balmung";
        Aether["Cactuar"] = "Cactuar";
        Aether["Coeurl"] = "Coeurl";
        Aether["Faerie"] = "Faerie";
        Aether["Gilgamesh"] = "Gilgamesh";
        Aether["Goblin"] = "Goblin";
        Aether["Jenova"] = "Jenova";
        Aether["Mateus"] = "Mateus";
        Aether["Midgardsormr"] = "Midgardsormr";
        Aether["Sargatanas"] = "Sargatanas";
        Aether["Siren"] = "Siren";
        Aether["Zalera"] = "Zalera";
    })(Aether = Worlds.Aether || (Worlds.Aether = {}));
    let Primal;
    (function (Primal) {
        Primal["Behemoth"] = "Behemoth";
        Primal["Brynhildr"] = "Brynhildr";
        Primal["Diabolos"] = "Diabolos";
        Primal["Excalibur"] = "Excalibur";
        Primal["Exodus"] = "Exodus";
        Primal["Famfrit"] = "Famfrit";
        Primal["Hyperion"] = "Hyperion";
        Primal["Lamia"] = "Lamia";
        Primal["Leviathan"] = "Leviathan";
        Primal["Malboro"] = "Malboro";
        Primal["Ultros"] = "Ultros";
    })(Primal = Worlds.Primal || (Worlds.Primal = {}));
    let Chaos;
    (function (Chaos) {
        Chaos["Cerberus"] = "Cerberus";
        Chaos["Lich"] = "Lich";
        Chaos["Louisoix"] = "Louisoix";
        Chaos["Moogle"] = "Moogle";
        Chaos["Odin"] = "Odin";
        Chaos["Omega"] = "Omega";
        Chaos["Phoenix"] = "Phoenix";
        Chaos["Ragnarok"] = "Ragnarok";
        Chaos["Shiva"] = "Shiva";
        Chaos["Zodiark"] = "Zodiark";
    })(Chaos = Worlds.Chaos || (Worlds.Chaos = {}));
    Worlds.AllWorlds = Object.values(Chaos).concat(Object.values(Primal), Object.values(Aether), Object.values(Mana), Object.values(Gaia), Object.values(Elemental));
})(Worlds = exports.Worlds || (exports.Worlds = {}));
